version: "3"
services:
    frontend:
        container_name: reactjs
        build:
            context: ./
            dockerfile: Dockerfile
        image: myproject
        ports:
            - "3000:3000"
        volumes:
            - ./:/usr/src/app